export const STUDIO_WIDTH = 1600;
export const STUDIO_HEIGHT = 900;
export const DRIVE_CHUNK_SIZE = 8 * 1024 * 1024;
export const MARKER_TYPES = Object.freeze({chapter:"Chương mới",important:"Quan trọng",practice:"Thực hành",cut:"Cắt lỗi",cta:"Kêu gọi hành động"});
const TRANSITIONS={draft:new Set(["ready","recording","archived"]),ready:new Set(["recording","archived"]),recording:new Set(["paused","processing","ready"]),paused:new Set(["recording","processing","ready"]),processing:new Set(["ready","uploaded","failed"]),uploaded:new Set(["ready","archived"]),failed:new Set(["ready","processing","archived"]),archived:new Set()};
export function slugify(value,fallback="buoi-hoc"){const result=String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,72);return result||fallback;}
export function safeFilename(name,extension=""){const ext=extension?String(extension).replace(/^\./,""):"";const base=slugify(String(name).replace(/\.[^.]+$/,""));
return ext?`${base}.${ext}`:base;}
export function createSession(title="Buổi học mới",now=Date.now(),random=Math.random){const id=`session-${now}-${Math.floor(random()*1e8).toString(36)}`;return{schemaVersion:1,id,title:String(title).trim()||"Buổi học mới",slug:slugify(title),state:"draft",createdAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString(),recording:null,markers:[],media:null,drive:null};}
export function transitionSession(session,nextState,now=Date.now()){if(!session||!TRANSITIONS[session.state])throw new Error("Trạng thái phiên không hợp lệ");if(!TRANSITIONS[session.state].has(nextState))throw new Error(`Không thể chuyển phiên từ ${session.state} sang ${nextState}`);return{...session,state:nextState,updatedAt:new Date(now).toISOString()};}
export function createMarker(type,atSeconds,label="",now=Date.now()){if(!MARKER_TYPES[type])throw new Error(`Loại marker không hợp lệ: ${type}`);const at=Math.max(0,Number(atSeconds)||0);return{id:`marker-${now}-${Math.round(at*1000)}`,type,label:String(label).trim()||MARKER_TYPES[type],at:Number(at.toFixed(3)),createdAt:new Date(now).toISOString()};}
export function mergeRanges(ranges,gap=.08){const sorted=(ranges||[]).map(r=>({start:Math.max(0,Number(r.start)||0),end:Math.max(0,Number(r.end)||0)})).filter(r=>r.end>r.start).sort((a,b)=>a.start-b.start||a.end-b.end);const out=[];for(const range of sorted){const last=out.at(-1);if(!last||range.start>last.end+gap)out.push({...range});else last.end=Math.max(last.end,range.end);}return out;}
export function subtractRanges(baseRanges,cutRanges){const cuts=mergeRanges(cutRanges,0),out=[];for(const base of mergeRanges(baseRanges,0)){let fragments=[{...base}];for(const cut of cuts){const next=[];for(const fragment of fragments){if(cut.end<=fragment.start||cut.start>=fragment.end){next.push(fragment);continue;}if(cut.start>fragment.start)next.push({start:fragment.start,end:Math.min(cut.start,fragment.end)});if(cut.end<fragment.end)next.push({start:Math.max(cut.end,fragment.start),end:fragment.end});}fragments=next;}out.push(...fragments.filter(f=>f.end-f.start>=.12));}return out;}
export function markerWindows(markers,duration,options={}){const total=Math.max(0,Number(duration)||0);const padding={chapter:[2,8],important:[4,10],practice:[5,14],cut:[2,3],cta:[3,10],...(options.padding||{})};const grouped={chapter:[],important:[],practice:[],cut:[],cta:[]};for(const marker of markers||[]){if(!grouped[marker.type])continue;const[before,after]=padding[marker.type],at=Math.min(total,Math.max(0,Number(marker.at)||0));grouped[marker.type].push({start:Math.max(0,at-before),end:Math.min(total,at+after)});}for(const key of Object.keys(grouped))grouped[key]=mergeRanges(grouped[key]);return grouped;}
export function buildRenderPlan({duration,markers=[],sessionId="unknown"}){const total=Math.max(0,Number(duration)||0);if(total<=0)throw new Error("Thời lượng bản ghi phải lớn hơn 0");const windows=markerWindows(markers,total);const master=subtractRanges([{start:0,end:total}],windows.cut);const highlight=subtractRanges(mergeRanges([...windows.chapter,...windows.important,...windows.practice,...windows.cta]),windows.cut);return{schemaVersion:1,sessionId,duration:Number(total.toFixed(3)),master,highlight,cuts:windows.cut,generatedAt:new Date().toISOString()};}
export function chooseMimeType(isSupported=()=>false){return["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm","video/mp4;codecs=h264,aac","video/mp4"].find(type=>{try{return Boolean(isSupported(type));}catch{return false;}})||"";}
export function qualityPreset(name="1080p"){const presets={"720p":{width:1280,height:720,fps:30,videoBitsPerSecond:3500000,audioBitsPerSecond:128000},"1080p":{width:1920,height:1080,fps:30,videoBitsPerSecond:6500000,audioBitsPerSecond:160000},"1080p-high":{width:1920,height:1080,fps:60,videoBitsPerSecond:10000000,audioBitsPerSecond:192000}};return{...(presets[name]||presets["1080p"])};}
export function containRect(sourceWidth,sourceHeight,targetWidth,targetHeight){const sw=Math.max(1,Number(sourceWidth)||1),sh=Math.max(1,Number(sourceHeight)||1),tw=Math.max(1,Number(targetWidth)||1),th=Math.max(1,Number(targetHeight)||1),scale=Math.min(tw/sw,th/sh),width=sw*scale,height=sh*scale;return{x:(tw-width)/2,y:(th-height)/2,width,height,scale};}
export function mapClientPoint(clientX,clientY,rect,width=STUDIO_WIDTH,height=STUDIO_HEIGHT){if(!rect||rect.width<=0||rect.height<=0)return{x:0,y:0};const x=((Number(clientX)-rect.left)/rect.width)*width,y=((Number(clientY)-rect.top)/rect.height)*height;return{x:Math.max(0,Math.min(width,x)),y:Math.max(0,Math.min(height,y))};}
export function chunkRanges(size,chunkSize=DRIVE_CHUNK_SIZE){const total=Math.max(0,Math.floor(Number(size)||0)),step=Math.max(256*1024,Math.floor(Number(chunkSize)||DRIVE_CHUNK_SIZE)),ranges=[];for(let start=0;start<total;start+=step){const endExclusive=Math.min(total,start+step);ranges.push({start,endExclusive,endInclusive:endExclusive-1,total});}return ranges;}
export function isRetryableStatus(status){const code=Number(status);return code===408||code===409||code===425||code===429||code>=500;}
export function formatDuration(seconds){const value=Math.max(0,Math.floor(Number(seconds)||0)),hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60),secs=value%60;return hours>0?[hours,minutes,secs].map(v=>String(v).padStart(2,"0")).join(":"):[minutes,secs].map(v=>String(v).padStart(2,"0")).join(":");}
export function formatBytes(bytes){const value=Math.max(0,Number(bytes)||0);if(value<1024)return`${value} B`;const units=["KB","MB","GB","TB"];let current=value/1024,index=0;while(current>=1024&&index<units.length-1){current/=1024;index++;}return`${current.toFixed(current>=10?1:2)} ${units[index]}`;}
export function buildManifest(session,{duration=0,mimeType="video/webm",chunkCount=0,size=0,scene=null}={}){if(!session?.id)throw new Error("Thiếu phiên học");return{schemaVersion:1,session:{...session,markers:[...(session.markers||[])]},recording:{duration:Number((Number(duration)||0).toFixed(3)),mimeType,chunkCount:Math.max(0,Math.floor(chunkCount)),size:Math.max(0,Math.floor(size))},scene:scene?{schemaVersion:1,...scene}:null,exportedAt:new Date().toISOString()};}
